version: "3.7"
services:
  nest:
    container_name: gcs-back
    build:
      dockerfile: 'Dockerfile'
      context: '.'
    ports:
      - "${NEST_EXTERNAL_PORT}:${NEST_INNER_PORT}"
    volumes:
        - ".:${WORKDIR}"
    working_dir: ${WORKDIR}
    command: sh -c "yarn install && yarn start:dev"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${ADMINER_ROOT_USER}
      POSTGRES_PASSWORD: ${ADMINER_ROOT_PASSWORD}
      POSTGRES_DB: ${PG_DEFAULT_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_EXTERNAL_PORT}:${ADMINER_INNER_PORT}"